//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirohubServicesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileCompany
    {
        public int ProfileID { get; set; }
        public int CompanyID { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<int> EmployeeCountID { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<decimal> GrossRevenue { get; set; }
        public Nullable<decimal> OperatingMargin { get; set; }
        public Nullable<decimal> NetMargin { get; set; }
        public Nullable<decimal> TotalAssets { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
