//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirohubServicesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearsExperienceLookup
    {
        public int YearsExperienceID { get; set; }
        public int YearsExperience { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
